apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gigaci
  namespace: argocd
spec:
  project:  default
  source:
    helm:
      valueFiles:
        - jcasc-us.yaml
        - continuous-mail-template-cm.yaml
        - release-mail-template-cm.yaml
    repoURL: 'git@github.com:Gigaspaces/xap-umbrella-chart.git'
    path: gigaumbrella
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: neptun
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
